### ISSUE TITLE
the courses disappear when on small screens

### ISSUE THREAD

**Issue by Sara-Samer** [andrewezzat21/Udemy-homepage#1]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/36432332/183963448-6973bbf6-c951-4b0c-ace2-c88b2cd9bb1d.png">

**Comment by Sara-Samer** [comment]
that's all, great code by the way!

**Comment by andrewezzat21** [comment]
Fixed the issue! thanks for the feedback
